### ISSUE TITLE
TODOS by Page (visuals)

### ISSUE THREAD

**Issue by Torvec** [markthos/wedloc#126]
- [x] Home: Implement AOS in subtle ways and get some images/video to populate it's section of the page, each section will talk about a specific use for the site/app and end with a call to action at the bottom
- [x] Sign Up: Fix the background image extending the page (want the footer visible on desktop)
- [x] Log In: Fix the background image extending the page (want the footer visible on desktop)
- [x] About Us: Do a writeup for the about the project section, write something about each member, implement AOS in subtle ways to enhance the visuals of the page. Get some screenshots of the app in progress, etc.
- [x] Payment: Convert all styles to tailwind css and match the styling of the rest of the site
- [x] Event Creator: Looks good, maybe add a title like "Create an Event" above the form container
- [x] My Events: Add event profile pic to each event, improve design slightly (looks a little sparse)
- [x] My Profile: Has issues with mobile view that need to be fixed
- [x] Event Space: Try to get the images/video to be a 1:1 square aspect ratio, make the event profile pic smaller in mobile (shrink 50%?)
- [x] Single View: Needs to be bigger in desktop view, add event header
- [x] Live Chat: Needs to be bigger in desktop view, add event header
- [x] QR Code: Add back button, small tweaks so it looks good on mobile and desktop

**Comment by Torvec** [comment]
fixed:
- Sign Up: Fix the background image extending the page (want the footer visible on desktop)
- Log In: Fix the background image extending the page (want the footer visible on desktop)

**Comment by JaKrau** [comment]
fixed:

* Event Creator: Looks good, maybe add a title like "Create an Event" above the form container

**Comment by Torvec** [comment]
DONE
